version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node # the primary container, where your job's commands are run
         # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" #
      - run: yarn install --frozen-lockfile
      - run: yarn test